### ISSUE TITLE
Publishing and contributing

### ISSUE THREAD

**Issue by richardaum** [riccardoperra/mswjs-devtools-extension#6]
Hey there!

I hope you're doing well. I recently stumbled upon your fantastic Chrome extension for MSW.js integration, and I must say, I'm quite impressed with the functionality it brings. It's such a useful tool that I believe many developers would benefit from.

I couldn't help but notice that the extension hasn't been published yet, and I was wondering if there's a specific reason for that. I'd like to express my interest in helping you further develop and refine this library in my spare time. Your work has the potential to make a significant impact, and I'd love to be a part of its growth.

If there are any challenges or tasks that are hindering the publication of the extension, please feel free to share them with me. I'm more than willing to contribute and collaborate with you to see this project through.

Let's chat about how we can move forward with this. Your expertise combined with my enthusiasm could lead to something truly remarkable. Looking forward to hearing from you and potentially working together on this exciting project!

Best regards,
Richard

**Comment by riccardoperra** [comment]
Hi, the extension is not published yet since it's currently not stable. there are somw things to be done.

i wrote a comment some weeks ago 
https://github.com/riccardoperra/mswjs-devtools-extension/discussions/4#discussioncomment-7092342
